---
version: '3.6'
services:
  nestjs:
    build: .
    container_name: nestjs
    command: npm run start:dev
    environment:
      - DATABASE_DIALECT=mysql
      - DATABASE_HOST=mysql
      - DATABASE_USERNAME=root
      - DATABASE_PASSWORD=root
      - DATABASE_PORT=3306
      - DATABASE_NAME=nestjs
    networks:
      - imersao-fullcycle
    ports:
      - 3000:3000
    volumes:
      - .:/app
      - /app/node_modules

networks:
  imersao-fullcycle:
    external: true
